version: "3.4"

services:
  bitly-fastify:
    build: .
    restart: "no"
    volumes:
      - ./:/usr/app
    ports:
      - 4000:4000
    depends_on:
      - database-fastify
      - flyway-fastify
    env_file:
      - project.env

  database-fastify:
    container_name: dab-p1-database-fastify
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway-fastify:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database-fastify
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
