version: "3.4"

services:
  bitly-express:
    build: .
    restart: "no"
    volumes:
      - ./:/usr/app
    ports:
      - 4000:4000
    depends_on:
      - database-express
      - flyway-express
    env_file:
      - project.env

  database-express:
    container_name: dab-p1-database-express
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway-express:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database-express
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
