version: "3.4"

services:
  bitly:
    build: .
    restart: "no"
    volumes:
      - ./:/usr/app
    ports:
      - 4000:4000
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: dab-p1-database-1b3da8a6-8f97-4a9f-956b-34b997d5f686
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
